import type { Metadata } from "next";
import { ConvexClientProvider } from "@/app/layout/components/ConvexClientProvider";
import "./App.css";
import "./globals.css";
import { Footer } from "./layout/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>
          {children}
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
