import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ConvexClientProvider } from "@/app/layout/components/ConvexClientProvider";
import "./App.css";
import "./globals.css";
import FooterHandler from "./layout/components/FooterHandler";

const raleway = Raleway({
  weight: ["400", "500"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={raleway.className}>
      <body>
        <ConvexClientProvider>
          {children}
        <FooterHandler />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
